title: Vikram Ramesh
logo: /site_assets/profile-round.png
description: Business Analyst | Product Owner
# show_downloads: true
theme: jekyll-theme-minimal
# remote_theme: pages-themes/minimal@v0.2.0
# plugins: - jekyll-remote-theme # add this line to the plugins list if you already have one
